version: '2'
services:
  server:
    environment:
      - 'NODE_ENV=production'
      - 'POSTGRES_HOST=postgres'
      - 'POSTGRES_PORT=5432'
      - 'PORT=3000'
    image: 'fridjon14/tictactoe:${GIT_COMMIT}'
    ports:
     - "80:3000"
     - "8084:80"
    links:
     - 'postgres'
  postgres:
    image: postgres
    environment:
     - 'POSTGRES_USER=postgres'
     - 'POSTGRES_PASSWORD=mysecretpassword'
    ports:
     - "5433:5432"